// <auto-generated />
using BulkyWebRazor_temp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWebRazor_temp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240501121830_CatgeoryTableToDB")]
    partial class CatgeoryTableToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWebRazor_temp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 3,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Check"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 7,
                            Name = "Time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
